

TRUNCATE TABLE flights ;
LOAD DATA INFILE "E:/MySQL/NYCFLIGHTS-13/Flights.Rda/flights.csv"
INTO TABLE flights
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
ignore 1 lines
;
SHOW WARNINGS ;


TRUNCATE TABLE airlines ;
LOAD DATA INFILE "E:/MySQL/NYCFLIGHTS-13/Flights.Rda/airlines.csv"
INTO TABLE airlines
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
ignore 1 lines
;
SHOW WARNINGS ;


TRUNCATE TABLE planes ;
LOAD DATA LOCAL INFILE "E:/MySQL/NYCFLIGHTS-13/Flights.Rda/planes.csv"
INTO TABLE planes
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
ignore 1 lines
;
SHOW WARNINGS ;


TRUNCATE TABLE airports;

LOAD DATA INFILE "E:/MySQL/NYCFLIGHTS-13/Flights.Rda/airports.csv"
INTO TABLE airports
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
ignore 1 lines
;
SHOW WARNINGS ;


TRUNCATE TABLE weather ;

LOAD DATA INFILE "E:/MySQL/NYCFLIGHTS-13/Flights.Rda/weather.csv"
INTO TABLE weather
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
ignore 1 lines
;
SHOW WARNINGS ;


-- CREATION DES PK
ALTER TABLE flights ADD id_flight INT PRIMARY KEY AUTO_INCREMENT FIRST ;


-- CREATION DES FK
-- FK ??
ALTER TABLE flights
ADD CONSTRAINT FK_origin
FOREIGN KEY (origin) REFERENCES airports(faa);


ALTER TABLE flights
ADD CONSTRAINT FK_dest
FOREIGN KEY (dest) REFERENCES airports(faa);


-- PENSE BETE
--  SET GLOBAL local_infile = 'ON';
ALTER TABLE flights DROP COLUMN id_flight ;